In [1]:
import numpy as np
import pandas as pd

# 1.1 Set up the data

To start working download the banking dataset on Kaggle.

In [2]:
data = pd.read_csv("bank_transactions.csv")

In [3]:
data

TransactionID CustomerID CustomerDOB CustGender   CustLocation  \
0                  T1   C5841053     10/1/94          F     JAMSHEDPUR   
1                  T2   C2142763      4/4/57          M        JHAJJAR   
2                  T3   C4417068    26/11/96          F         MUMBAI   
3                  T4   C5342380     14/9/73          F         MUMBAI   
4                  T5   C9031234     24/3/88          F    NAVI MUMBAI   
...               ...        ...         ...        ...            ...   
1048562      T1048563   C8020229      8/4/90          M      NEW DELHI   
1048563      T1048564   C6459278     20/2/92          M         NASHIK   
1048564      T1048565   C6412354     18/5/89          M      HYDERABAD   
1048565      T1048566   C6420483     30/8/78          M  VISAKHAPATNAM   
1048566      T1048567   C8337524      5/3/84          M           PUNE   

         CustAccountBalance TransactionDate  TransactionTime  \
0                  17819.05          2/8/16           143207   
1                   2270.69          2/8/16           141858   
2                  17874.44          2/8/16           142712   
3                 866503.21          2/8/16           142714   
4                   6714.43          2/8/16           181156   
...                     ...             ...              ...   
1048562             7635.19         18/9/16           184824   
1048563            27311.42         18/9/16           183734   
1048564           221757.06         18/9/16           183313   
1048565            10117.87         18/9/16           184706   
1048566            75734.42         18/9/16           181222   

         TransactionAmount (INR)  
0                           25.0  
1                        27999.0  
2                          459.0  
3                         2060.0  
4                         1762.5  
...                          ...  
1048562                    799.0  
1048563                    460.0  
1048564                    770.0  
1048565                   1000.0  
1048566                   1166.0  

[1048567 rows x 9 columns]

For the sake of this first part, not all columns are necessary since comparing each field single handedly can be quite time-expensive. Then, carefully read the linked guide above and try to understand which features will be appropriate for this task (An heads up: some users have more than one transaction record, make sure to handle them all). Once you have finished, project a version of the dataset to work with.

In [26]:
data2 = data.drop(['TransactionID','CustomerID'],axis=1)

In [27]:
data2

CustomerDOB CustGender   CustLocation  CustAccountBalance  \
0           10/1/94          F     JAMSHEDPUR            17819.05   
1            4/4/57          M        JHAJJAR             2270.69   
2          26/11/96          F         MUMBAI            17874.44   
3           14/9/73          F         MUMBAI           866503.21   
4           24/3/88          F    NAVI MUMBAI             6714.43   
...             ...        ...            ...                 ...   
1048562      8/4/90          M      NEW DELHI             7635.19   
1048563     20/2/92          M         NASHIK            27311.42   
1048564     18/5/89          M      HYDERABAD           221757.06   
1048565     30/8/78          M  VISAKHAPATNAM            10117.87   
1048566      5/3/84          M           PUNE            75734.42   

        TransactionDate  TransactionTime  TransactionAmount (INR)  
0                2/8/16           143207                     25.0  
1                2/8/16           141858                  27999.0  
2                2/8/16           142712                    459.0  
3                2/8/16           142714                   2060.0  
4                2/8/16           181156                   1762.5  
...                 ...              ...                      ...  
1048562         18/9/16           184824                    799.0  
1048563         18/9/16           183734                    460.0  
1048564         18/9/16           183313                    770.0  
1048565         18/9/16           184706                   1000.0  
1048566         18/9/16           181222                   1166.0  

[1041614 rows x 7 columns]

# 1.2 Fingerprint hashing

Implement your minhash function from scratch. No ready-made hash functions are allowed. Read the class material and search the internet if you need to. For reference, it may be practical to look at the description of hash functions in the book.

In [4]:
data.dropna(inplace=True)

In [22]:
def minhash(set,n_perm):
    sign = np.zeros([n_perm+1,len(set[0])])
    for i in range(3):
        j = 0
        while set[j][i] == 0:
             j += 1
        sign[0][i] = j+1  
    for b in range(0,n_perm):
        set = np.random.permutation(set)
        print(set)
        for i in range(3):
            j = 0
            while set[j][i] == 0:
                j += 1
            sign[b+1][i] = j+1
    return sign        

In [23]:
a=[[1,0,0],[0,1,0],[1,1,0],[0,0,1]]
minhash(a,2)

[[1 0 0]
 [1 1 0]
 [0 0 1]
 [0 1 0]]
[[1 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]


array([[1., 2., 4.],
       [1., 2., 3.],
       [1., 1., 4.]])